export type AnimationTypes = {
    component: () => React.JSX.Element | undefined;
    name: string;
    id: number;
    title: string;
    category: string;
    video: string;
    image: string;
    color: string;
    sourcePath: string;
    description: string;
    sectionBefore: boolean;
    sectionAfter: boolean;
    librairies: string[];
    html: string[];
    htmlCode: string;
    javascript: string[];
    javascriptMethods: string[];
    javascriptCode: string;
    animation: string[];
    animationMethods: string[];
    gsapCode: string;
    githubLink: string;
};